logo: "/images/ProfilePic.jpg?raw=true" # your photo (or logo) here
title: Joe D. Lewis # your name (or website title) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <a href="https://www.linkedin.com/in/joe-lewis-9882b1224/"> My LinkedIn Profile </a>
  <br><br>
  Aircraft Engineering BEng(Hons) at 2:1
  <br>
  <i>University of the West of Scotland<i>
  <br><br>
  Aerospace Engineering PGCert
  <br>
  <i>University of Glasgow<i>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
