title: Joe D. Lewis # your name (or website title) here
logo: "/images/ProfilePic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  University of the West of Scotland: Aircraft Engineer BEng (Hons)
  <br><br>
  University of Glasgow: Aerospace Engineering PGCert
  <br><br>
  <a href="https://www.linkedin.com/in/joe-lewis-9882b1224/"> My LinkedIn Profile </a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
